In [1]:
from pandas import read_csv 
import numpy as np

In [23]:
df = read_csv('international-airline-passengers.csv')
def f(str1):
    no = str1[-2:]
    return no
df["1mor"] = df.Month.apply(f)
df.drop("Month",axis = 1, inplace = True)
df

,International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60,1mor
0,112,01
1,118,02
2,132,03
3,129,04
4,121,05
5,135,06
6,148,07
7,148,08
8,136,09
9,119,10
10,104,11
11,118,12
12,115,01
13,126,02
14,141,03
15,135,04
16,125,05
17,149,06
18,170,07
19,170,08
20,158,09
21,133,10
22,114,11
23,140,12
24,145,01
25,150,02
26,178,03
27,163,04
28,172,05
29,178,06
...,...,...
114,491,07
115,505,08
116,404,09
117,359,10
118,310,11
119,337,12
120,360,01
121,342,02
122,406,03
123,396,04
124,420,05
125,472,06
126,548,07
127,559,08
128,463,09
129,407,10
130,362,11
131,405,12
132,417,01
133,391,02
134,419,03
135,461,04
136,472,05
137,535,06
138,622,07
139,606,08
140,508,09
141,461,10
142,390,11
143,432,12

In [25]:
values = df.values.astype('Float32')
values.shape

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.

(144, 2)

In [27]:
train_size = int((values.shape[0] * 0.67))
test_size = values.shape[0]  - train_size
train = values[0:train_size]
test = values[train_size:]

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range =(0,1))
train = scaler.fit_transform(train)
test = scaler.transform(test)

In [29]:
def create_dataset(data, k):
    dataX, dataY = [],[]
    for i in range(data.shape[0] - k):
        x = []
        for j in range(i,i+k):
            l = [data[j,0],data[j,1]]
            x.append(l)
        #x = data[i:i + k, 1]
        y = data[i + k, 1]
        dataX.append(x)
        dataY.append(y)
    return np.array(dataX), np.array(dataY)

In [30]:
look_back = 12
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)

In [34]:
trainX.shape

(84, 12, 2)

In [10]:
trainX = np.reshape(trainX, (trainX.shape[0], trainX.shape[1], 2))
testX = np.reshape(testX, (testX.shape[0], testX.shape[1], 2))
trainX.shape

ValueError: cannot reshape array of size 1008 into shape (84,12,2)

In [17]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense

Using TensorFlow backend.

In [32]:
model = Sequential()
model.add(SimpleRNN(4, input_shape=(look_back, 2)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=10, batch_size = 1)
model.summary()

Epoch 1/10
84/84 [==============================] - 1s 6ms/step - loss: 1.1441
Epoch 2/10
84/84 [==============================] - 0s 3ms/step - loss: 0.3333
Epoch 3/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1912
Epoch 4/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1699
Epoch 5/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1597
Epoch 6/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1503
Epoch 7/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1426
Epoch 8/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1360
Epoch 9/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1278
Epoch 10/10
84/84 [==============================] - 0s 3ms/step - loss: 0.1209
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
simple_rnn_3 (SimpleRNN)     (None, 4)                 28
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 5
=================================================================
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________

In [35]:
score = model.evaluate(testX,testY)
score

36/36 [==============================] - 0s 2ms/step

0.24453067117267185